name: chinook
recipe: laravel
config:
  webroot: public
  database: postgres
  build:
    - yarn install
  command: yarn dev
services:
  node:
    type: node
    build:
      - npm install
tooling:
  npm:
    service: node
  node:
    service: node
  yarn:
    service: node
