name: chinook
recipe: laravel
config:
  webroot: public
  database: postgres
services:
  node:
    type: node
    build:
      - npm install
tooling:
  npm:
    service: node
  node:
    service: node
